### ISSUE TITLE
replace feature name parsing with a feature graph

### ISSUE THREAD

**Issue by plger** [shortRNAhub/shortRNA#6]
Right now the hierarchical relationship between features is parsed from the features' ids at different moments:
- during annotation preparation
- during read assignment
- during read aggregation

This is redundant, tied to the specific annotation used, and limited to 3 hierarchical levels. We need to replace this with a proper, generalizable feature tree that the users will be able to customize. This is a bit tricky and I have the solution already so I'll take care of it.

- [ ] automatically generate feature tree from annotation files
- [ ] implement feature tree to find common ancestor in read assignment
- [ ] implement feature tree during aggregation

**Comment by dktanwar** [comment]
this is done!
