### ISSUE TITLE
`dbplyr` related error

### ISSUE THREAD

**Issue by dktanwar** [shortRNAhub/shortRNA#73]
Tried with 2 different versions of `dbplyr`

- 2.5.0
- 2.4.0

```R
ah <- AnnotationHub::AnnotationHub()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by plger** [comment]
you just have to update AnnotationHub

**Comment by dktanwar** [comment]
I am trying that. I need to update to newest version of Bioconductor as well.

On 10 Jun 2024, at 16:16, Pierre-Luc ***@***.***> wrote:



you just have to update AnnotationHub

**Comment by plger** [comment]
you can also just update using the github version, it worked on my older bioc
